### PR TITLE
Allow to set IP in configuration

### PR DESCRIPTION
**Pull request by ErnestStaug**
I would suggest to allow users to set IP in configuration instead of trying to fetch with a command (which does not work and always will get internal docker ip).

### CODE REVIEW

**Comment by felipecrs** [comment]
It's meant to get the internal docker ip, what's wrong with that?

**Comment by felipecrs** [comment]
Also, check this: https://github.com/TECH7Fox/Asterisk-add-on/blob/8e013b65afe23aee212a503c5253de15dfc449f6/asterisk/DOCS.md#configuring-the-asterisk-integration

**Comment by ErnestStaug** [comment]
> It's meant to get the internal docker ip, what's wrong with that?

Sorry, but I don't understand why?
What is the point limiting connections only to it's own internal container IP (172.17. x.x), while https://github.com/TECH7Fox/Asterisk-integration is trying to connect with HA IP in LAN scope (192.168.x.x).
image

Or I should use different IP for integration? (IF it's using addon-on container ip, integration should get it automatically, as users wont be able to get containers IP)

**Comment by felipecrs** [comment]
Did you check the link I provided? It's working for me this way.

**Comment by felipecrs** [comment]
I.e.: can you try to setup the integration with host as `b35499aa-asterisk` and check if you still have issues making it connect? We can enhance documentation later.

**Pull request closed without merging**
