### PR TITLE
Video support

### PR DESCRIPTION
**Pull request by pergolafabio**

### CODE REVIEW

**Comment by felipecrs** [comment]
@pergolafabio just wondering, did you test? Here is how to do so: https://developers.home-assistant.io/docs/add-ons/testing

**Comment by pergolafabio** [comment]
No, didn't test yet, but not at home :-(

**Comment by felipecrs** [comment]
Right... unfortunately I don't have a working setup just yet. Otherwise I would test it too.

**Comment by felipecrs** [comment]
You will need to update this PR with the latest revision of main branch... The file that you changed was moved to another place.

**Comment by pergolafabio** [comment]
Ok, will create another PR, once I can make manually sip extensions in the conf files... Because with the current extensions , I can't use them with softphones...

Manually adding extensions was next on the list it seems?

**Pull request closed without merging**
