### PR TITLE
Setup CI

### PR DESCRIPTION
**Pull request by felipecrs**
Closes #19

### CODE REVIEW

**Comment by felipecrs** [comment]
I just wonder how this will work as your GitHub user has uppercase characters.

**Comment by TECH7Fox** [comment]
> I just wonder how this will work as your GitHub user has uppercase characters.

What do you mean?

**Comment by felipecrs** [comment]
Docker registries can't be like that

**Comment by TECH7Fox** [comment]
Ah. Can we test this before merging?

**Comment by felipecrs** [comment]
Some notes:

- While developing comment out the 'image' key from 'example/config.yaml' to make the supervisor build the addon
  - Remember to put this back when pushing up your changes.
- When you merge to the 'main' branch of your repository a new build will be triggered.
  - Make sure you adjust the 'version' key in 'example/config.yaml' when you do that.
  - Make sure you update 'example/CHANGELOG.md' when you do that.
  - The first time this runs you might need to adjust the image configuration on github container registry to make it public

**Comment by felipecrs** [comment]
I added a potential fix for the uppercase thing. I think it can be merged now. :)

**Comment by felipecrs** [comment]
I could test this in my own repo, but I would need to change back the image repository to `felipecrs`...

**Pull request merged**
