### PR TITLE
Include settings for hints

### PR DESCRIPTION
**Pull request by TECH7Fox**

### CODE REVIEW

**Comment by TECH7Fox** [comment]
Need a way to hint all the extensions in the dialplan, like the dial function.

Looked at [this](https://serverfault.com/questions/809064/asterisk-cant-dial-if-hints-are-used) but it wasn't working for me.

**Comment by TECH7Fox** [comment]
This is btw also for the integration, to get the state.

**Comment by TECH7Fox** [comment]
The change in `sip_default.conf` will make the state busy instead of inUse and allow it to subscribe, but the card doesn't use that yet. (Would be cool to see the state of other extensions in the card)

inUse means it's in a call but can accept more calls, while busy means it is in the amount of calls set in busylevel=1. [Here](https://wiki.asterisk.org/wiki/display/AST/Asterisk+13+ManagerEvent_ExtensionStatus) are all the states.

**Comment by felipecrs** [comment]
Interesting... looks really nice.

**Pull request merged**
