### PR TITLE
Configure certificate like other add-ons

### PR DESCRIPTION
**Pull request by felipecrs**
References https://github.com/home-assistant/addons/blob/master/nginx_proxy/config.yaml#L18 and https://github.com/home-assistant/addons/blob/master/letsencrypt/config.yaml#L19.

So that, we leverage the generation of the certificate to Let's Encrypt add-on, like the rest of the add-ons.

With this, chances are that certificates will be configured without having to change anything for most HA installations.

### CODE REVIEW

**Comment by TECH7Fox** [comment]
So if people don't have a certificate already, they have to use the Let's encrypt add-on?

**Comment by felipecrs** [comment]
> So if people don't have a certificate already, they have to use the Let's encrypt add-on?

Exactly. That's how many other add-ons works today. Examples:

https://github.com/home-assistant/addons/tree/master/nginx_proxy
https://github.com/hassio-addons/addon-tasmoadmin/tree/main/tasmoadmin

**Comment by TECH7Fox** [comment]
Aha, alright. Can you also remove openssl from the Dockerfile? Not used anymore.

**Comment by felipecrs** [comment]
Done

**Pull request merged**
