### PR TITLE
v0.3.3

### PR DESCRIPTION
**Pull request by felipecrs**
- [x] Fix changelog
- [x] Change version in config.yaml
- [x] #41

### CODE REVIEW

**Review by TECH7Fox — APPROVED** [review]

**Comment by felipecrs** [comment]
Now it's good to merge, I think, but it would be nice if someone could test first using the "local testing" trick.

**Comment by TECH7Fox** [comment]
> Now it's good to merge, I think, but it would be nice if someone could test first using the "local testing" trick.

I'm testing now.

**Comment by TECH7Fox** [comment]
Got this:
```
2022/01/06 14:49:31 template: tempIO:29:10: executing "tempIO" at <.auto_add_secret>: can't evaluate field auto_add_secret in type interface {}
```

**Comment by felipecrs** [comment]
Hm.. I think I know what's wrong.. try something like this:

```
{{ if .auto_add }}
{{ $secret := .auto_add_secret }}
{{  range $index, $person := .persons }}
{{   $extension := add 100 $index }}
[{{ $extension }}](sipjs-phone,my-codecs)
username={{ $extension }}
secret={{ $secret }}
callerid="{{ $person }}" <{{ $extension }}>
{{   end }}
{{ end }}
```

I think the global context is lost after entering a `range` block, thus `auto_add_secret` would not be available there.

**Comment by TECH7Fox** [comment]
You are right! It works now.

But I did notice something else. When I try to start without changing the default secret, it won't start and gives a error.

**Comment by TECH7Fox** [comment]
Changing the default secret to `1234abcd` seems to work.

**Comment by felipecrs** [comment]
I think that if you write

``` 
auto_add_secret: "1234"
```

It will also work. That's because otherwise YAML thinks it's a number.

**Pull request merged**
