### PR TITLE
Remove extra space from discovery configuration

### PR DESCRIPTION
**Pull request by TECH7Fox**
Just trying some things

### CODE REVIEW

**Comment by felipecrs** [comment]
I don't know why GitHub is showing all these commits. Could you run: `git fetch && git merge origin/develop && git push`?

**Comment by TECH7Fox** [comment]
Did that, everything up to date. Don't know what's up with it...

**Comment by felipecrs** [comment]
One sec, let me fix for you.

**Comment by TECH7Fox** [comment]
No everything is there, only removed that space. But didn't fix the discovery error. Looked some more at the supervisor, integrations and some addons code but couldn't find anything.

**Comment by felipecrs** [comment]
@TECH7Fox I think this is what you need to register in the integration:

https://developers.home-assistant.io/docs/dev_101_services/

**Comment by TECH7Fox** [comment]
Will try that tomorrow. Thanks!

**Comment by felipecrs** [comment]
Well lets merge this, after all it removes a space which were not meant to be there. Also, I think the only work required now will be at the integration side.

**Pull request merged**
