### PR TITLE
Disable TLS by default

### PR DESCRIPTION
**Pull request by TECH7Fox**
Disable TLS by default. Otherwise every custom extension needs to add tlsenable=no.

We should leave the rest so people can still easily add TLS.

### CODE REVIEW

**Comment by felipecrs** [comment]
I have this:

```
[8001]
type=friend
host=dynamic
context=default
transport=udp
username=8001
secret=b4jB6brjD2
disallow=all
canreinvite=yes
allow=alaw
allow=ulaw
allow=h264
videosupport=yes
insecure=invite
dtmfmode=info
callerid="Video Porteiro" <8001>
```

Which does not have `tlsenable=no` and still works fine...

**Comment by felipecrs** [comment]
I have this:

```
[8001]
type=friend
host=dynamic
context=default
transport=udp
username=8001
secret=1234
disallow=all
canreinvite=yes
allow=alaw
allow=ulaw
allow=h264
videosupport=yes
insecure=invite
dtmfmode=info
callerid="Video Porteiro" <8001>
```

Which does not have `tlsenable=no` and still works fine...

**Comment by TECH7Fox** [comment]
You probaly still have the old `sip.conf` file. That file doesn't get overwritten. (So people can change [general] easily.)

**Comment by felipecrs** [comment]
https://user-images.githubusercontent.com/29582865/155577363-a26a20a0-9189-4cc2-8b6c-9a178b0c681e.mp4

**Comment by TECH7Fox** [comment]
Hmm... And you don't get a error like `TLS not a valid transport`? Someone in the discord had that problem and was fixed by adding `tlsenable=no`.

**Comment by TECH7Fox** [comment]
`sip_custom.conf`

```
[8001]
type=friend
host=dynamic
context=default
transport=udp
username=8001
secret=null
callerid="test" <8001>

[8002]
type=friend
host=dynamic
context=default
transport=udp
username=8002
secret=null
callerid="test2" <8002>
```

Logs:

image

**Comment by felipecrs** [comment]
Perhaps the user is configuring the device to connect into Asterisk's port 5160 rather than 5060?

**Comment by TECH7Fox** [comment]
He used the card.

image

Weird... I will hold this merge back for now. Maybe more people will experience this problem, or maybe it was a rare situation.

**Comment by felipecrs** [comment]
There must be something else wrong then, because the card connects through WSS and not through TLS.

**Comment by TECH7Fox** [comment]
Now you say it, he also used zoiper for extension `8001`. But no idea how it was configured.

**Comment by TECH7Fox** [comment]
Now you say it, he also used zoiper for extension `8001`. But no idea how it was configured.

**Comment by TECH7Fox** [comment]
Now you say it, he also used zoiper for extension `8001`. But no idea how it was configured.

**Comment by TECH7Fox** [comment]
Closing because I never heard other people have problems with this, and pjsip is coming.

**Pull request closed without merging**
