### PR TITLE
Setup AMI

### PR DESCRIPTION
**Pull request by felipecrs**

### CODE REVIEW

**Comment by felipecrs** [comment]
@TECH7Fox the integration is able to connect with the add-on now. This is how I configured the integration:

image

Where host is the hostname that supervisor shows for Asterisk add-on.

**Comment by pergolafabio** [comment]
And what do you use for password?

**Comment by felipecrs** [comment]
You set it in the addon configuration

**Comment by pergolafabio** [comment]
Ah, you maybe update the readme with an example, usefull for everyone then

**Comment by felipecrs** [comment]
Definitely, but I would prefer to have a full working scenario... later I will try to make SIP calls to see if they work. There are a lot of things to shave after that...

**Comment by pergolafabio** [comment]
I only see below in options

**Comment by felipecrs** [comment]
image

**Comment by pergolafabio** [comment]
Thnx, clear

**Comment by felipecrs** [comment]
Guys, don't forget to delete the whole `/config/asterisk` folder before re-installing the add-on. Otherwise the new configuration will not be applied.

**Pull request merged**
