### PR TITLE
Add option for disabling SSL

### LINKED ISSUE #65: Allow for non-SSL installation for reverse proxy users
This project looks to be a sorely needed integration for Home Assistant and I have been watching the vast amount of improvements that have been made in a short amount of time.

I can install this add-on without issue, but because I run Nginx outside of Home Assistant, no certificates are stored on my Home Assistant machine.  If I manually add the certificates to the /ssl directory, the add-on will start and I can add the integration, but any attempt at connection results in SSL errors.

If there is a way to get this add-on to work without local SSL certs, that would be greatly appreciated as I use reverse proxy for just a couple of machines.

### PR DESCRIPTION
**Pull request by felipecrs**
Closes #65

### CODE REVIEW

**Comment by felipecrs** [comment]
The code currently handles the WebSockets interface only. But I also saw some references in sip.conf and sip_default.conf which I suppose should be omitted as well. I just don't know what are the implications of doing so.

@TECH7Fox any clue?

**Comment by TECH7Fox** [comment]
The webrtc/sipjs extensions won’t work without ssl, because browsers don’t allow that. So removing that in sip_default will break them. The ssl option in general (sip.conf) is only used for custom extensions. So that can be optional.

I don’t think there is any way to use webrtc without ssl. I tried many times before.

A ssl option could be useful if you don't plan on using the card.
- sip_default.conf: Check if both ssl and auto generate are on before making the extensions.
- sip.conf: make the entire ssl part optional.

**Comment by felipecrs** [comment]
It's okay, SSL is being disabled because the SSL layer will be added later by NGINX.

**Comment by felipecrs** [comment]
After disabling SSL, one would configure the NGINX to proxy http://192.168.1.x:8088 behind a HTTPS. Then one would configure the SIP TLS card with something like: https://my-nginx-endpoing.mydomain.com/ws

**Comment by felipecrs** [comment]
If you want to give it a try, check: https://sip-home.felipecrs.com/ws. Under the hoods it's forwarding to 
 8088: image
 
In my case, I'm using [Cloudflared](https://github.com/brenner-tobias/addon-cloudflared), but it also uses NGINX under the hoods.

**Comment by TECH7Fox** [comment]
Ah, alright.

don’t know if webrtc works if you remove dtls. Asterisk may give problems, but you can try.

**Comment by felipecrs** [comment]
So, from what I understood, I can go ahead and also disable stuff like:

image

image

If SSL is disabled. Right?

**Comment by felipecrs** [comment]
Got it. Will try. Thanks.

**Comment by TECH7Fox** [comment]
Did you test this?

**Comment by felipecrs** [comment]
No no, and it's not ready as well. If you plan to release a new version soon, don't wait for this one.

**Comment by TECH7Fox** [comment]
Alright, will update to 1.0.0.

**Pull request merged**
